[server]
port = 8080
enableCORS = true
headless = true
maxUploadSize = 1000

[browser]
gatherUsageStats = false

[global]
server.enableXsrfProtection = false

[server.timeout]
websocketTimeout = 600000
